#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
# auto_upgrade = true
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = 'p:white'
    background = 'transparent'
    template = '{{ if .WSL }}WSL at {{ end }} {{.Icon}} '

    [blocks.segments.properties]
      linux = "\uF17C \uF30e"
      # mint = "\uF30e"
      # debian = "\uF306"

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:blue'
    template = '{{ path .Path .Location }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:green'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:green{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'p:white'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    template = ' {{ if gt .Code 0 }}{{.Code}} {{ else }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:green'
    background = 'transparent'
    template = '{{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = 'p:green'
    background = 'transparent'
    template = ' '

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'
    template = ' '

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'p:white'
    background = 'transparent'
    template = '<p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[[tooltips]]
  type = 'aws'
  tips = ['aws']
  style = 'diamond'
  foreground = 'p:white'
  background = 'p:orange'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '

  [tooltips.properties]
    display_default = true

[[tooltips]]
  type = 'az'
  tips = ['az']
  style = 'diamond'
  foreground = 'p:white'
  background = 'p:blue'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '

  [tooltips.properties]
    display_default = true

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '{{"\n"}}❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
